const phone='+12172937410', phoneText='+1 (217) 293-7410';
const services=[
['leak-detection-repair.html','Leak Detection & Repair','Find the source, protect your home.','leak.jpg'],['drain-cleaning.html','Drain Cleaning & Clog Removal','Clear drains without the runaround.','drain.jpg'],['water-heater.html','Water Heater Installation & Repair','Reliable hot water, restored.','water-heater.avif'],['toilet-repair.html','Toilet Repair & Installation','A bathroom that works the way it should.','toilet.jpeg'],['faucet-fixtures.html','Faucet & Fixture Replacement','Stop drips and refresh your space.','faucet.jpg'],['pipe-repair-repiping.html','Pipe Repair & Whole-House Repiping','Durable solutions for your plumbing system.','pipes.avif'],['sump-pumps.html','Sump Pump Maintenance & Installation','Keep water where it belongs.','sump.jpg'],['sewer-lines.html','Sewer Line Inspection & Repair','Get answers before a sewer issue grows.','sewer.avif']];
const page=location.pathname.split('/').pop()||'index.html';
const serviceLinks=services.map(s=>`<a href="${s[0]}">${s[1]}</a>`).join('');
document.querySelectorAll('[data-header]').forEach(el=>el.innerHTML=`<div class="utility"><div class="wrap"><span>Serving Hoffman Estates, IL & Surrounding Communities</span><span>Open 24/7 · Free estimate</span></div></div><header class="header"><div class="wrap nav"><a class="brand" href="index.html"><span class="brand-mark">✦</span>Quick Plumbing</a><button class="mobile-toggle" aria-label="Open navigation">☰</button><nav class="nav-links"><a href="index.html">Home</a><div class="drop"><button>Services ▾</button><div class="menu">${serviceLinks}</div></div><a href="emergency.html">24/7 Emergency</a><a href="about.html">Why Choose Us</a><a href="contact.html">Contact</a></nav><a class="call" href="tel:${phone}">Call Now</a></div></header>`);
document.querySelector('.mobile-toggle')?.addEventListener('click',()=>document.querySelector('.nav-links').classList.toggle('open'));
document.querySelectorAll('[data-footer]').forEach(el=>el.innerHTML=`<footer class="footer"><div class="wrap footer-grid"><div><a class="brand" href="index.html"><span class="brand-mark">✦</span>Quick Plumbing</a><p>Clear answers and dependable plumbing help for Hoffman Estates homes and businesses.</p><a class="call" href="tel:${phone}">Call Now: ${phoneText}</a></div><div><h3>Services</h3>${services.slice(0,4).map(s=>`<a href="${s[0]}">${s[1]}</a>`).join('')}</div><div><h3>Contact</h3><a href="tel:${phone}">${phoneText}</a><a href="mailto:contact@hoffmanestatesplumber.com">contact@hoffmanestatesplumber.com</a><p>095-2119 Stonington Ave<br>Hoffman Estates, IL 60169</p><p>Open 24/7</p></div></div><div class="wrap legal"><span>© ${new Date().getFullYear()} Quick Plumbing. All rights reserved.</span><span>hoffmanestatesplumber.com</span></div></footer>`);
document.querySelectorAll('[data-service-cards]').forEach(el=>el.innerHTML=services.map(s=>`<article class="card"><img src="assets/${s[3]}" alt="${s[1]} service"><div class="card-body"><h3>${s[1]}</h3><p>${s[2]}</p><a class="text-link" href="${s[0]}">Learn more →</a></div></article>`).join(''));
document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const n=f.querySelector('[name=name]')?.value||'there';f.innerHTML=`<div class="notice">Thanks, ${n}. Your request is ready to be sent to Quick Plumbing. For urgent plumbing help, please call <a href="tel:${phone}">${phoneText}</a>.</div>`}));
